# version: "2"

# services: 
#   consul1:
#     build: .
#     command: 'agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -node=consul1 -log-level=debug'
#     ports:
#       - '8300:8300'
#       - '8301:8301'
#       - '8302:8302'
#       - '8400:8400'
#       - '8500:8500'
#       - '8600:53/udp'
#     container_name: 'consul1'
#     depends_on:
#       - gin-web-01
#       - gin-web-02
#     networks:
#       - docker-consul
#   gin-web-01:
#     image: gin-web:1.0.1
#     environment: 
#       - PORT=8080
#     ports: 
#       - "8080:8080"
#     networks:
#       - docker-consul
#   gin-web-02:
#     image: gin-web:1.0.1
#     environment: 
#       - PORT=9090
#     ports: 
#       - "9090:9090"    
#     networks:
#       - docker-consul

# networks:
#   docker-consul:
#     driver: bridge


version: '3'

services:
  consul1:
    build: .
    command: 'agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -node=consul1 -log-level=debug'
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8302:8302'
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    container_name: 'consul1'
    depends_on:
      - gin-web-01
      - gin-web-02
    networks:
      - docker-consul
  gin-web-01:
    image: gin-web:1.0.1
    environment: 
      - PORT=8080
    ports: 
      - "8080:8080"
    networks:
      - docker-consul
  gin-web-02:
    image: gin-web:1.0.1
    environment: 
      - PORT=9090
    ports: 
      - "9090:9090"    
    networks:
      - docker-consul

networks:
  docker-consul:
    driver: bridge
